[tool.poetry]
name = "datapipe"
version = "0.7.0"
description = ""
authors = ["Andrey Tatarinov <a@tatarinov.co>"]

exclude=["tests", "examples"]

[tool.poetry.dependencies]
python = "^3.8"
fsspec = "==2021.5.0"
gcsfs = "==2021.5.0"

pandas = ">=1.1.4"
SQLAlchemy = ">=1.3.20, <1.4"
psycopg2_binary = ">=2.8.4"
cloudpickle = ">=1.6.0"
PyYAML = ">=5.3.1"
Pillow = ">=7.2.0, <8"
tqdm = ">=4.60.0"
toml = ">=0.10.2"
click = ">=7.1.2"
requests = ">= 2.24.0"

xlrd = ">=2.0.1"
openpyxl = ">=3.0.7"

dash = ">=1.20.0"
dash_bootstrap_components = ">= 0.12.0"
dash_interactive_graphviz = ">=0.3.0"

label-studio = "==1.0.1"

[tool.poetry.dev-dependencies]
pytest = "*"
flake8 = "^3.9.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
