# CronJob template
# for each .Values.loops item, create a cronjob
{{ $image := .Values.image }}
{{ $resources := .Values.resources }}

{{- range .Values.loops }}

apiVersion: batch/v1
kind: CronJob
metadata: 
  name: {{ .name }}
spec:
  schedule: "{{ .schedule }}"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{ .name }}
            image: "{{ $image.repository }}:{{ $image.tag }}"
            command:
              - datapipe
              - step
              - --labels={{ .labels }}
              - run
            {{- if .resources }}
            resources: {{ .resources | toYaml | nindent 14 }}
            {{- else if $resources }}
            resources: {{ $resources | toYaml | nindent 14 }}
            {{- end }}
          restartPolicy: OnFailure
          {{- if .nodeSelector }}
          nodeSelector: {{ .nodeSelector | toYaml | nindent 10 }}
          {{- end }}
          {{- if .tolerations }}
          tolerations: {{ .tolerations | toYaml | nindent 10 }}
          {{- end }}
          {{- if .affinity }}
          affinity: {{ .affinity | toYaml | nindent 10 }}
          {{- end }}
          {{- if .serviceAccountName }}
          serviceAccountName: {{ .serviceAccountName }}
          {{- end }}
          {{- if .securityContext }}
          securityContext: {{ .securityContext | toYaml | nindent 10 }}
          {{- end }}
          {{- if .imagePullSecrets }}
          imagePullSecrets: {{ .imagePullSecrets | toYaml | nindent 10 }}
          {{- end }}

--- 
{{- end }}
